### ISSUE TITLE
Consider contributing to uBlock filters – Annoyances

### ISSUE THREAD

**Issue by anewuser** [yourduskquibbles/webannoyances#10]
uBlock Origin now has an official _Annoyances_ list:  https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt.

It'd be better if you reported or submitted missing rules from existing _Annoyance_ lists directly to the uAssets repository for the benefit of all users.

**Comment by elypter** [comment]
the majority of the filters in this list are floating headers. the ubo annoyances list might not see those as annoyances and i think it is better to keep those two separate so a user can chose what he wants to block

**Comment by anewuser** [comment]
uBlock Origin can overwrite CSS styles to make those headers permanent instead of removing them altogether (if that's what this list currently does), and I believe uBO Annoyances isn't enabled by default (will check later), so it's more flexible than other native lists.

**Comment by Ravizz** [comment]
@elypter,

please don't listen to this troll, watch this first:
https://github.com/gorhill/uBlock/issues/3489
https://github.com/NanoAdblocker/NanoCore/issues/116

in other words, keep developing this great filter lists, do not succumb to competition attacks.

**Comment by anewuser** [comment]
@Ravizz  for some reason, you're under the impression that people create open source projects for selfish reasons, and that they work like companies trying to eliminate each other. I wonder how you even ended up on Github.

The idea of open source is to **share** and **contribute** towards a **common goal**. There's no "competition" or conspiracy. @yourduskquibbles created this repository _to help uBlock Origin_ by making a kind of list that it didn't have, and I made this post as a heads-up that there's no need to keep a separate repository anymore, since uBlock Origin has added an _Annoyances_ list, and he can contribute to it directly. This will actually give his work more exposure. 

Also, different open source projects that "compete" for the same userbase are actually open to helping each other, like uBlock Origin and Nano Adblocker and AdGuard. The developers of all these projects just want to help as many as people to achieve a goal (in this case, blocking ads/trackers), and they don't care if you use their own open source code or somebody's else to achieve this goal. 

Everyone involved with these projects actually get happy with the more users the "competition" has, because it means  more people being able to block ans and trackers, and that's all we want.

**Comment by elypter** [comment]
@anewuser
>There's no "competition" or conspiracy.

to be honest this looks like a powergrab. i have nothing against merging list with the same purpose if it makes life easier for everyone but first the source of the filters is a different one so there is not much overlapping and second the purpose is quite different because it focuses mostly on floating headers. in a perfect world each list would have its own niche and no overlaps. while this list is not perfect your suggestion doesnt make it better but worse.

i also find it kind of weird that a bunch of people are talking about the fate of this list while the developer probably hasnt even read all these posts

**Comment by anewuser** [comment]
It is the weird that *you* are using words like "troll" and "powergrab" before the maintainer hasn't even read it yet. Just stop arguing and let he reply. He'll understand the point of my post, since it was directed at him.

**Comment by jspenguin2017** [comment]
@anewuser Although open source projects are certainly not trying to eliminate each other, I wouldn't say there is no competition. Each project, even forks, likely have different goals and values, as otherwise they would have been a single project.

**Comment by anewuser** [comment]
@jspenguin2017 of course, they often have their own reasons to exist separately and "compete" in a broader sense. When I said "no competition", I was talking about  what @Ravizz   has been posting around, equalizing voluntary projects with companies.  He has edited the post I replied to here. It included a link to an article about competition laws in Europe or something.

**Comment by yourduskquibbles** [comment]
I have no issue merging this list with uBlock Annoyance list if that is what @gorhill wants.

That being said, the original intent of this filterlist is somewhat different scope from other Annoyance lists in that my main purpose for creating it was to have a list to pin floating elements on a site using CSS style tags. Most annoyance lists I have seen just remove social elements and don't address floating headers, sticky headers, floating nav bars, etc.

I also try to avoid generic cosmetic filters (those with no domain prefix) due to performance implications @gorhill has brought up multiple times. For example, check the number of generic filters in [my list](https://github.com/yourduskquibbles/webannoyances/raw/master/ultralist.txt) (29) vs [Adguard Annoyances list ](https://filters.adtidy.org/extension/chromium/filters/14.txt)(1,500+) or [Fanboy Annoyances List ](https://easylist.to/easylist/fanboy-annoyance.txt)(20,000+).

**Comment by yourduskquibbles** [comment]
This topic discussion makes me think that I may need to make some more site demonstration gifs/videos in the github overview section to show websites before/after with the list disabled/enabled to easily see if the functionality offered by this list is what users would want.

Many people who add this list may not even realize what this list is doing to most sites since it is working behind-the-scenes and making their web usage more enjoyable by changing the behavior of annoying cosmetic elements.

**Comment by anewuser** [comment]
I'm sorry for making the mistake of not just saying "hey, what about sending **patches** to this new list?". I instead said "close" and caused a lot of misunderstandings from your users.

If you're still interested in contributing to the new list, you can send a sample "header pin" patch for a specific site to see if people agree with adding such a rule to the list.

**Comment by yourduskquibbles** [comment]
Leaving this open for a bit to allow for more debate.

**Comment by elypter** [comment]
what i personally would like the best is if all the non floating element pinning rules moved to the ubo repository and the floating elements get an own list.

a more general opinion about rule hosting is that i would avoid hosting rules and adblockers on the same repository or by the same person because that makes things more vulnerable and allows for potential conflicts if an adblocker uses a list that is hosted by another adblocker project.

**Comment by yourduskquibbles** [comment]
Just an FYI, I have added a [wiki entry](https://github.com/yourduskquibbles/webannoyances/wiki/Demonstration-of-Web-Annoyances-Ultralist) to visually demonstrate the purpose of this filter list.

If any of you following this thread would be so kind, I would appreciate feedback on the wiki both negative or positive.

**Comment by yourduskquibbles** [comment]
Thanks for feedback! Will close this issue now.
