### ISSUE TITLE
Medium.com

### ISSUE THREAD

**Issue by Avery3R** [yourduskquibbles/webannoyances#130]
### URL(s) where the issue occurs

`https://medium.com/@seandexter1/wireframes-are-becoming-less-relevant-and-thats-a-good-thing-e66b30724a27`

### Describe the issue

Sticky header, sticky footer, and after you read 5 or so articles on medium.com it'll show you a pop up and disable scrolling.

### Versions

- Browser/version: FF 65.0.1
- uBlock Origin version: 1.18.4

### Settings

No changes

### Notes

The sticky header has the `metabar` class, and the sticky footer has the `u-fixed` class.

**Comment by yourduskquibbles** [comment]
@Avery3R I think all of what you describe should be covered within the sublists that are loaded when you subscribe to the Ultralist using the [One-Click Installation ](https://github.com/yourduskquibbles/webannoyances#one-click-installation)

Is it possible you have disabled cosmetic filtering in uBO either for all sites, or for `medium.com`?

To check for this, are you able to confirm your uBO Settings look like the following:

Popup panel should have no slash through the eye icon when you open your [medium.com example site](https://medium.com/@seandexter1/wireframes-are-becoming-less-relevant-and-thats-a-good-thing-e66b30724a27)
![cosmeticfiltering](https://user-images.githubusercontent.com/22258847/53540818-0f4ae880-3ae5-11e9-8691-076ef77f75ca.png)

Filter Lists tab of settings should look like the following:
![filter_lists](https://user-images.githubusercontent.com/22258847/53540847-2e497a80-3ae5-11e9-97b1-d3ae27791e9a.PNG)


If you see a slash through the eye icon when you open your example site, go under the `My Rules` tab of setting and delete the rule `no-cosmetic-filtering: medium.com true` under `Temporary Rules` column and then Commit the change to make your change permanent. After doing this, reload the [medium.com example site](https://medium.com/@seandexter1/wireframes-are-becoming-less-relevant-and-thats-a-good-thing-e66b30724a27) and confirm all issues described above are fixed.

For reference:
The sticky header should be pinned to the top with the following filter from the [CSS style filter sublist](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/css_style_filters.txt) 
```
500ish.com,artplusmarketing.com,atrium.co,backchannel.com,bitcointechtalk.com,bitwarden.com,blazingdb.com,blog.devcolor.org,blog.confiant.com,blog.growthhackers.com,blog.hiri.com,blog.ltse.com,blog.statebox.org,blog.twitch.tv,bluerockpublicradio.com,bolt.io,boomsupersonic.com,bradfieldcs.com,brightthemag.com,checkio.org,citizen428.net,coach.me,discordapp.com,doist.com,doit-intl.com,dotandline.net,doublepulsar.com,economist.com,electricliterature.com,elidourado.com,esciencecenter.nl,fossa.io,freecodecamp.org,fritz.ai,getadblock.com,greylock.com,hackernoon.com,headmelted.com,helium.com,howwegettonext.com,iheart.com,injusticetoday.com,insightdatascience.com,iota.org,itnext.io,itsyourturnblog.com,jupyter.org,kiwi.com,learngoprogramming.com,learningbyshipping.com,ledwards.com,legalist.com,logrocket.com,mapbox.com,medium.com,melmagazine.com,mondaynote.com,newco.co,nytimes.com,nyulocal.com,ofdollarsanddata.com,okmeter.io,postlight.com,prototypr.io,rainway.io,sagefy.org,signalvnoise.com,slackhq.com,springboard.com,standardnotes.org,startupsventurecapital.com,stoplight.io,tech.buzzfeed.com,theabacus.io,theawl.com,thebigroundtable.com,thebillfold.com,thecontrol.co,theringer.com,thinkprogress.org,thriveglobal.com,timeline.com,towardsdatascience.com,udacity.com,unpatent.co,usejournal.com,uxdesign.cc,uxplanet.org,warisboring.com,wearemel.com,whatahowler.com,x.company##.js-metabar:style(position: absolute !important;)
```


The sticky footer should be removed in the [generic filter sublist](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/generic_filters.txt) with the filter
```
 ##.js-stickyFooter
```

The article read count overlay popup and scrolling function broken should be removed and fixed with the following three filters from the [modal filter sublist](https://raw.githubusercontent.com/yourduskquibbles/webannoyances/master/filters/modal_filters.txt)
```
backchannel.com,centurylink.net,medium.com,mondaynote.com,thriveglobal.com,uxplanet.org##.popover
bedbathandbeyond.com,hackernoon.com,medium.com,realcleardefense.com,realclearpolitics.com,thehindubusinessline.com,vice.com##.overlay
99bitcoins.com,africacheck.org,alexa.com,amctheatres.com,betterhelp.com,breitbart.com,brioni.com,buckscountycouriertimes.com,burlingtoncountytimes.com,businessinsider.com,change.org,china-underground.com,chron.com,cigarinspector.com,citylab.com,coinstaker.com,dewalt.com,discovermagazine.com,eastbaytimes.com,ew.com,fair.org,filmcomment.com,forzieri.com,geniuskitchen.com,hackernoon.com,hindustantimes.com,iphonelife.com,jcutrer.com,kerbalspaceprogram.com,leaf.tv,lightstalking.com,mamapedia.com,medium.com,mongodb.com,motor-talk.de,newsbtc.com,newseum.org,otakustream.tv,paper.li,publicdomainreview.org,rankedboost.com,readfrontier.org,revisionisthistory.com,searchenginewatch.com,seekingalpha.com,shopstyle.com,slamonline.com,spiceworks.com,syfy.com,techwalla.com,thedailybeast.com,thedailybell.com,theintell.com,themefoxx.com,thespoon.tech,toptal.com,trefiel.com,usatoday.com,washingtonmonthly.com,watchpro.com,williams-sonoma.com,yodalearning.com##html:style(overflow-x: hidden !important; overflow-y: scroll !important;)
```

**Comment by Avery3R** [comment]
Issue was on my end, sorry. Thank you for the detailed response.

**Comment by yourduskquibbles** [comment]
No problem, glad to hear you got it fixed!
