### ISSUE TITLE
nytimes.com

### ISSUE THREAD

**Issue by rdsu-pt** [yourduskquibbles/webannoyances#206]
### URL(s) where the issue occurs

https://www.nytimes.com/interactive/2020/03/23/world/coronavirus-great-empty.html

### Describe the issue

It just appear the image of Paris city. If you scroll down the images about the other cities didn't load.

### Versions

- Vivaldi 2.11.1811.49 (Stable channel) (64-bit)
- uBlock Origin 1.24.4

### Settings

- default settings

### Notes

I found that this rule block those images:
nytimes.com##html:style(overflow-x: hidden !important; overflow-y: auto !important; padding-right: 0 !important;)

from "Web Annoyances Ultralist - Modal Overlay Filters"

**Comment by yourduskquibbles** [comment]
@rdsu-pt  Thanks for reporting, I think this was behaviour described is being caused by commit https://github.com/yourduskquibbles/webannoyances/commit/93b4976988f368f4b6284e97c568a5b310a9a9dd which I have reverted.

Do you mind updating filters and letting me know if you still have issue? I removed the `position: relative` being set on `##.interactive-masthead` and think that this fixes the issue you described.

**Comment by rdsu-pt** [comment]
I forgot to mention that I only use:
Web Annoyances Ultralist - Ad Placeholder Filters​​​​​
Web Annoyances Ultralist - Modal Overlay Filters​​​​​
Web Annoyances Ultralist - Newsletter Subscription Filters

I still saw this in the logs:
![2020-03-24_14h52_21](https://user-images.githubusercontent.com/10651797/77439814-710c7d80-6ddf-11ea-853e-5938206e2bd8.png)

When I disable this list, it works fine.

Thanks for your support!

**Comment by yourduskquibbles** [comment]
OK let me test with that setup and see what I can come up with. I'd like keep that filter in the modal list as I know that there are modal popups on nytimes.com that will take away the scroll behaviour but I may be able to find a better series of selectors or exclude this type of page from the `html` filter.

**Comment by yourduskquibbles** [comment]
I will deploy this filter `nytimes.com##html:not(.nytapp-vi-interactive):style(overflow-x: hidden !important; overflow-y: auto !important; padding-right: 0 !important;)` now to modal list which should solve your problem. 

I will also personally test this filter for a few days and try to trigger a modal popup on one of their pages to verify users won't lose their scroll bar on other pages with no way to get it back with this filter.

**Comment by rdsu-pt** [comment]
It's working now. Thanks!

**Comment by yourduskquibbles** [comment]
I've added some additional filters to the modal list in commit https://github.com/yourduskquibbles/webannoyances/commit/3793b190f23bf7654bc6087afb172fb288223942 that should allow reading of coronavirus related articles without being forced to login. (This may help on other types of articles but I won't fully know until this madness is over with... and `nytimes.com` is back to their normal site behaviour) From my testing, this should help when not using other extensions such as [`bypass-paywalls-chrome-clean`](https://github.com/magnolia1234/bypass-paywalls-chrome-clean) or [`bypass-paywalls-firefox-clean`](https://github.com/magnolia1234/bypass-paywalls-firefox-clean).

@rdsu-pt do you mind continued testing and letting me know if this is breaking anything for you with just your filter list subscriptions?


Some example tested links that this should remove various footer bars / login prompts and scroll jacking/overlays from: 
1. `https://www.nytimes.com/2020/03/26/world/asia/afghanistan-iran-coronavirus.html`
2. `https://www.nytimes.com/interactive/2020/03/21/upshot/coronavirus-deaths-by-country.html`
3. `https://www.nytimes.com/2020/03/24/smarter-living/virus-remaking-space-while-homebound.html`
4. `https://www.nytimes.com/programs/productivity-challenge`
5. `https://www.nytimes.com/2020/03/23/smarter-living/why-mundane-moments-matter.html`

Cross-posting from: https://github.com/yourduskquibbles/webannoyances/issues/146#issuecomment-604424366

**Comment by rdsu-pt** [comment]
It seems good, I just have this footer bar:
![2020-03-26_14h53_45](https://user-images.githubusercontent.com/10651797/77660819-b19c0080-6f71-11ea-889b-a26da6dd781c.png)

**Comment by yourduskquibbles** [comment]
What article link are you seeing that on? Would like to remove that too if possible

**Comment by rdsu-pt** [comment]
All of them, except here:
https://www.nytimes.com/programs/productivity-challenge
![2020-03-26_15h10_59](https://user-images.githubusercontent.com/10651797/77662703-1e17ff00-6f74-11ea-8276-5e9d3183b8ec.png)

**Comment by yourduskquibbles** [comment]
Are you able to purge your filter list cache and update your modal filter list under `Filter Lists` section of uBO? i think these might be ones I've already fixed with previous commit https://github.com/yourduskquibbles/webannoyances/commit/3793b190f23bf7654bc6087afb172fb288223942 but guessing you may not have the most up to date version of the list loaded.

To verify you have latest list, you can click on the modal list subscription from filter lists tab which will open up the raw list that is loaded by UBO in new browser tab and verify your last modified time on second line is showing as  `! Last Modified: 10:24 2020-03-26`?

Screenshots below:

![Untitled](https://user-images.githubusercontent.com/22258847/77664106-3d9f2f80-6f54-11ea-98ad-a48a541261b0.png)

![Untitled2](https://user-images.githubusercontent.com/22258847/77664213-61fb0c00-6f54-11ea-8fab-780bf4615849.png)

**Comment by rdsu-pt** [comment]
Works fine after update the filter list! :)

**Comment by yourduskquibbles** [comment]
Thanks for confirming!
