### ISSUE TITLE
Google home page upside-down

### ISSUE THREAD

**Issue by Omoeba** [yourduskquibbles/webannoyances#247]
### URL(s) where the issue occurs

`www.google.com`

### Describe the issue

The google search bar appears over the logo/doodle instead of under it normally

### Screenshot(s)

![image](https://user-images.githubusercontent.com/38597972/91371079-edf3b700-e7c4-11ea-972c-0e03a63b9fcd.png)

### Notes

Tested with AdGuard for Windows on Chrome and AdGuard for Mac on Safari.

**Comment by krystian3w** [comment]
Yeah: "https://github.com/yourduskquibbles/webannoyances/blob/8b0b0ea22a7dd3a74eaa31dbd191ec5113102251/filters/floating_filters.txt#L3465" (no possible view other as raw).

Now problematic:
```
google.com###js-header, #searchform, .O-j-k, .header:not(.column-section):not(.viewed):not(.ng-star-inserted), .js-header.chr-header, .mobile-action-bar, body > .ng-scope, #flt-nav, .gws-flights__scrollbar-padding.gws-flights__selection-bar, .gws-flights__selection-bar-shadow-mask:style(position: absolute !important;)
```

**Comment by yourduskquibbles** [comment]
@Omoeba Thanks for reporting! It was indeed messed up, definitely not intentional! Should be fixed now, adguard should update the cached version of Web Annoyances list within next 12 hours or so (normally around 5pm EST) so you can use `www.google.com#@$##searchform { position: absolute !important; top: 20px !important; }` in your personal filter list until then if you would like

**Comment by Omoeba** [comment]
Thanks!
