### ISSUE TITLE
"Switch to Google" on non Google Chrome Browsers

### ISSUE THREAD

**Issue by prediscover** [yourduskquibbles/webannoyances#258]
I'm surprised this hasn't been reported :o 
Maybe it's difficult to tackle. I'm not too familiar with how custom filters work :(

### URL(s) where the issue occurs

www.google.com, https://www.google.com/maps/, https://calendar.google.com/ (basically all the google sites)
### Describe the issue

Using anything that's not Google Chrome, Google will popup this window 
### Screenshot(s)

<img width="1009" alt="Screenshot 2020-10-29 104719" src="https://user-images.githubusercontent.com/10902462/97612991-57ff2700-19d5-11eb-8d9b-f593e7b4fa24.png">

![](https://user-images.githubusercontent.com/10902462/97613154-91379700-19d5-11eb-9edd-1cc4011522d5.png)

### Versions

- Browser & Version: [Microsoft Edge Version 86.0.622.56, Firefox 82.0.2]
- Adblocker (uBlock Origin) & Version: [1.30.6]

### Settings

All Default settings except add this webannoyances list

### Notes

Every time I use the element picker; I notice that the filter is a different string of text so blocking it once only helps for a little while

**Comment by krystian3w** [comment]
Also AdGuard Annoyance idea down.

**Comment by yourduskquibbles** [comment]
Do you have to be logged in to google account to see this? I can't reproduce on non-logged to google firefox.

**Comment by yourduskquibbles** [comment]
@prediscover @krystian3w  I tried again using 2 different google accounts on firefox and can not get this to reproduce. Maybe non-US IP is required? Or is this a message that if dismissed once on google account will never show back up? I also have all activity controls "Paused" on both google accounts set under `https://myaccount.google.com/data-and-personalization` maybe they need to not be paused?

I'm not sure how to reproduce since I am not experiencing the same popup with stock uBO filters + Web Annoyances Ultralist as ONLY other list enabled.

So far tested and can't reproduce on:

1. `https://goo.gl/maps/nwQco9HSgXgV1fnd8`
2. `https://myaccount.google.com/data-and-personalization`
3. `https://calendar.google.com/calendar/u/0/r?pli=1`
4. `https://www.google.com/search?source=hp&ei=qbOiX9zlM-6lytMPmNK2yAQ&q=mansions+in+france&oq=mansions+in+france`

**Comment by krystian3w** [comment]
For my helped remove completely chromium Edge profile.

---

So bug like as A/B test.

**Comment by yourduskquibbles** [comment]
@krystian3w Thanks for tip on new profile in edge, that worked for me... 

I see a few filter options ordered from least to most aggressive, what do you think?

1. Maybe least aggressive filter option with like you suggest using just `[role]` and `[style]`
   * `google.com##iframe[role="presentation"][style="height: 100%; width: 100%;"]:upward(1)`
2. More aggressive than `1.` but I think this filter would also work,  but not sure if there is anything else google uses the `ogs.google.com` iframe for? 
   * `google.com##iframe[src*="ogs.google.com/widget"]:upward(1)`
3. Also possible network filter, but this probably most aggressive option:
   * `||ogs.google.com/widget/callout$subdocument,1p`

**Comment by yourduskquibbles** [comment]
`ogs.google.com` domain discussion: `https://old.reddit.com/r/privacy/comments/enjoiy/is_ogsgooglecom_a_safelegitimate_cookie/`

I think it is safest to go with approach `1.` `google.com##iframe[role="presentation"][style="height: 100%; width: 100%;"]:upward(1)` since I don't want to cause any authentication breakage possibility by adding a network filter to that domain - thoughts?

**Comment by krystian3w** [comment]
AdGuard used similar with subdomains:

```
calendar.google.com,docs.google.com,mail.google.com,news.google.com,drive.google.com##iframe[src^="https://ogs.google.com/widget/callout?prid="]:upward(div[style^="overflow: hidden; position: absolute; top: 0px; width:"])
```

**Comment by yourduskquibbles** [comment]
I'm going to add `google.com##iframe[role="presentation"][style="height: 100%; width: 100%;"]:upward(1)`

**Comment by yourduskquibbles** [comment]
Updated the filter to `google.com##iframe[role="presentation"][style="height: 100%; width: 100%;"][src*="ogs.google.com/widget/callout"]:upward(1)` to address #269
