### ISSUE TITLE
google.com floating toolbar and floating left aside

### ISSUE THREAD

**Issue by NovemLinguae** [yourduskquibbles/webannoyances#294]
### URL(s) where the issue occurs

https://www.google.com/search?q=california+covid+vaccine+phases

### Describe the issue

Topbar and left aside float.

### Screenshot(s)

![2021-03-19_101513](https://user-images.githubusercontent.com/79697282/111818350-4f33c280-889c-11eb-8a79-a89c2582d6be.png)

### Versions

- Browser & Version: Chrome, Windows 7, 1080p, 150% zoom
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: ubo dev

### Settings

- default + all annoyances + web annoyances ultralist + block everything

### Notes

I tried `google.com###searchform:style(position: static !important;)` but that didn't work.

**Comment by yourduskquibbles** [comment]
@NovemLinguae I think this should be fixed now however it may reappear since the class names are random. Hoping this doesn't break some other random google site by targeting to just `www.` "subdomain" of `google.com`. Please let me know if you are still having issues and I will try to come up with a better solution!
