### ISSUE TITLE
[feature suggestion] generic filter

### ISSUE THREAD

**Issue by elypter** [yourduskquibbles/webannoyances#3]
i dont know enough about the ublock syntax to judge if this is possible but it would be cool if you could create a short list that filters elements of a specific pattern on all websites. 

i thought about everything that has the style: position:fixed and a document path that contains keywords like: header, head, navbar, fixed, menu, navigation, sticky, logo, app, footer, locked...

this could be an additional more risky filter for those willing to risk breakage in favor of not being annoyed. however i still dont expect many false positives because it could only block elements with "position:fixed"

keyword list:

sticky
header
head
navigation
nav
fixed
fix
ribbon
logo
app
footer
locked
main
top
pinned
site(probably not a good idea to include that)
banner
social
share
sharing
shares
like
follow
login
signup (would not ad this)
sign-up (would not ad this)
signin (would not ad this)
sign-in (would not ad this)
teaser
tease
related
recommend
recommended
action
scrolled
stuck
smart
mobile
index
icon
pagenav
row
static
tray
global
rail
tab
float
floating
scrolled
menu
bar
bottom
panel
mast
master

these are often followed by:
menu, bar, header, head, main, top, banner, sticky navigation or nav

eg: sticky-bar, navbar or logosticky

**Comment by yourduskquibbles** [comment]
I don't know if I fully understand the request, but you could try testing how effective this would be on your own copy of ublock by adding the filters you list above as generic cosmetic filters (i.e. no domain name used but this has some ) under 'My filters'. There are performance implications by not using domain targeted cosmetic filters though because each filter has to be tested to see if it will work on *every* page load. 

[See this discussion](https://github.com/gorhill/uBlock/issues/1892) for more info on why I try to avoid using generic cosmetic filters as much as possible.

**Comment by elypter** [comment]
unfortunately i dont know how those filters work. the documentation is no help. for example i looked at one of the rules in the list: 2bigfeet.com##.nav-overflow:style(position: relative !important; top: 0 !important;)

when i inspect the header element nav-overflow the browser shows me position: absolute; and position: absolute; and i have no idea what !important means either.

maybe i can get my idea across if i write it with pseudo regexp mixed in:

##.(sticky|header|head|navigation|.....)[_-]?(menu|bar|header|.....)?:style(position:fixed)
       ^long list                                                          ^short list

**Comment by yourduskquibbles** [comment]
Hi @elypter sorry for the delay on getting back to you I wanted to do some proper research before replying. I don't think what you want is currently possible due to limitations in the `:style()` tag within uBlock Origin because `:style()` must be targeted at a specific domain and not just a generic cosmetic filter.

Please see uBlock writeup on [Static filter syntax: style section](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#style) for more information.

The relevant bit is: 

> As with the other new cosmetic filtering selectors, the :style can be used only for specific cosmetic filters, i.e. there must be a hostname of entity specified for the filter.

**Comment by elypter** [comment]
ah, ok, thanks for helping me.

**Comment by elypter** [comment]
if you are interested, i created a little script that generates a generic filterlist for the top 20 tlds and generic class/style names made from a list of prefixes and suffixes. it comes at the cost of being 2mb but it cleans up a fair amount of headers and i dont expect many false positives.

https://github.com/elypter/generic_annoying_stickybar_filter
