### ISSUE TITLE
Bloomberg share button and page ad

### ISSUE THREAD

**Issue by sweetcashew** [yourduskquibbles/webannoyances#330]
### URL(s) where the issue occurs

`https://www.bloomberg.com/news/articles/2021-07-27/blizzard-employees-call-for-strike-after-discrimination-lawsuit`

### Describe the issue

This filter removes the email share button and page ad block (contents are already removed, but this also removes the empty space) on article pages:
```
bloomberg.com##[class*="share-article-button"]
bloomberg.com##.sticky-container .page-ad
```

### Screenshot(s)

<img width="415" alt="image" src="https://user-images.githubusercontent.com/88003315/127382854-8c2f4c9c-e5b8-4df4-b50f-06bd7bbab6ac.png">

**Comment by yourduskquibbles** [comment]
@sweetcashew I normally leave share buttons for email if it uses a `mailto:` URI since this isn't a spam/marketing method as well as share buttons for link copying shortcut since I think those are useful for some people so I just focus on remove the plague of social network share buttons.

I'm going to leave the email share for now and think about if I want to start removing those or not. 

I added the ad filter and testing a fix for bloomberg articles on iOS with adguard where the page overlay is removed and unable to scroll in the meantime.

Need to take a break on issue fixes, will hopefully be able to get through the rest of your reports in next day or so.
