### ISSUE TITLE
theatlantic.com

### ISSUE THREAD

**Issue by Mennaruuk** [yourduskquibbles/webannoyances#354]
### URL(s) where the issue occurs

`https://www.theatlantic.com/culture/archive/2021/09/eagles-hotel-california-tour-review/619973`

### Describe the issue

Dickbar.

### Screenshot(s)

![image](https://user-images.githubusercontent.com/52135169/132107020-76e1afa5-b292-4856-a4e2-c844cd955847.png)

### Versions

- Browser & Version: Firefox 91.0.2
- Adblocker (uBlock Origin, Adguard, Nano Adblocker, etc.) & Version: uBlock Origin 1.37.2

### Settings

N/A

### Notes

Thanks again!

**Comment by Mennaruuk** [comment]
I think this filter should solve it!

`theatlantic.com###paywall`

**Comment by yourduskquibbles** [comment]
@Mennaruuk I think its a soft paywall

`theatlantic.com###paywall`
Tested and just adding the scroll bar back fixes it for me even after "too many" articles.

`theatlantic.com##body[class*="Gate"]:style(overflow: auto !important;)`

**Comment by yourduskquibbles** [comment]
@Mennaruuk Thx for reporting, and I think should be fixed, hopefully no issues for anyone just subscribing to only [`ad_placeholders.txt`](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/ad_placeholders.txt) list or [`modal_filters.txt`](https://github.com/yourduskquibbles/webannoyances/blob/master/filters/modal_filters.txt) list which is why I added to both sublists.

**Comment by Mennaruuk** [comment]
Bullseye! Works like a charm. Thanks again, champ :)
