### ISSUE TITLE
freshly.com broken share images

### ISSUE THREAD

**Issue by LanikSJ** [yourduskquibbles/webannoyances#461]
### URL(s) where the issue occurs

`https://www.freshly.com/refer?source=nav-bar`

### Describe the issue
The social icons under "Or share from" in middle of the page are missing.
The "Join Us" section on the bottom right hand side of the page is missing.

See the Notes section on how I fixed it.

### Screenshot(s)
Without the added exceptions:
![Screen Shot 2022-01-27 at 6 12 47 PM](https://user-images.githubusercontent.com/12159404/151475766-e6c242fd-9547-4d94-83a6-d255d4b60847.png)
WIth the added exceptions:
![Screen Shot 2022-01-27 at 6 13 15 PM](https://user-images.githubusercontent.com/12159404/151475781-04a152ba-9db1-4498-8624-f004b6c9997e.png)

### Versions

- Brave Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (x86_64)
- uBlock Origin & Version: 1.40.8

### Settings
![Screen Shot 2022-01-27 at 6 22 56 PM](https://user-images.githubusercontent.com/12159404/151476240-c849c40b-aa41-4f22-a180-5dd646904d17.png)
All Filters Updated.

### Notes
I was able to fix it with:
```
freshly.com#@#.social-button
freshly.com#@#.social-nav
```
`freshly.com#@#.social-button` fixes the icons under "Or share from" in middle of the page
`freshly.com#@#.social-nav` fixes the "Join Us" on the bottom right of the page.

**Comment by yourduskquibbles** [comment]
@LanikSJ Thanks for reporting! Looks like you need to have an account to test this properly but I trust the filters you provided so will update as you suggested.

**Comment by LanikSJ** [comment]
For the sake of transparency here are some screenshots.
![Screen Shot 2022-01-27 at 8 15 01 PM](https://user-images.githubusercontent.com/12159404/151486382-1cd69d22-fb92-4248-ba9b-bcb81cd247f8.png)
![Screen Shot 2022-01-27 at 8 15 17 PM](https://user-images.githubusercontent.com/12159404/151486384-87de6426-1815-4e7f-a77d-48bea57cd0ce.png)

**Comment by yourduskquibbles** [comment]
Thanks, but just for future reference I trust your work even if you weren't able to provide them. And besides it's not like a generic cosmetic filter is something particularly risky to add an exception filter for 😉

**Comment by andrewlental** [comment]
Hi LanikSJ,

I'm new to GitHub since I was directed to your script as a solution to a Facebook problem of videos popping out and only now discovered a means of contact you.

Firstly, may I say thank you so much for your efforts in making this script available. I've been searching for a solution such as yours for years without success.

Your script has been working as designed for many videos in my newsfeed but there are still quite a few that pop out. I'll collect a few examples and post again once I have them. Please keep up the excellent work, your efforts are very much appreciated.

Regards, Andrew
