### ISSUE TITLE
2 rules to fix

### ISSUE THREAD

**Issue by wmyrda** [yourduskquibbles/webannoyances#74]
[L5020](https://github.com/yourduskquibbles/webannoyances/blob/master/ultralist.txt#L5020)
`docs.microsoft.com#` probably needs two hashes instead of just one

[L8928](https://github.com/yourduskquibbles/webannoyances/blob/master/ultralist.txt#L8928) 
msn.com.## `.` after host name seems wrong. Adblock2privoxy converter thrown an error here two

**Comment by yourduskquibbles** [comment]
Thanks for reporting.

Just an FYI I removed the broken filter `msn.com.##.light.filmstrip` you reported because it would be a redundant/unnecessary filter after fixing seeing as there is already another rule in place with those DOM elements `msn.com##.light.filmstrip:style(position: relative !important; top: 0 !important;)`.
