### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by joejordan** [yourduskquibbles/webannoyances#82]
The Facebook search bar is normally sticky at the top of the screen as you scroll on Facebook. With this filter enabled, the search bar is fixed at the top of the page.

**Comment by yourduskquibbles** [comment]
Are you able to provide the filter you are suggesting or an example screenshot of what you are describing? I am not following the issue.

**Comment by joejordan** [comment]
As you can see in the gifs below, with the filter disabled, the FB search bar stays pinned to the top of the screen as you scroll. With the filter enabled, it is left at the top of the page and is not onscreen as you scroll down.
![2018-09-08_14-54-11](https://user-images.githubusercontent.com/997952/45257630-7a5a0480-b377-11e8-8d9c-396fa47b3882.gif)
![2018-09-08_14-51-47](https://user-images.githubusercontent.com/997952/45257631-7e862200-b377-11e8-8911-09cacf5915b7.gif)

**Comment by yourduskquibbles** [comment]
I believe what you are describing is intended behavior of the filter list. In general, all floating elements will be pinned as to reclaim lost screen real estate by floating elements. I am going to keep the filter that causes this behavior since it is a core tenant to what this filterlist is meant to achieve.

That being said, if you want to override the specific filter causing the search bar to stay pinned to the top of the screen on facebook add `facebook.com#@#._50ti:style(position: relative !important;)` to 'My Filters' in your uBlock settings. This will set a priority filter to ignore this specific filter in the list.

Please let me know if I've misunderstood what you are asking for.
